const assert = require('node:assert/strict');
const fs = require('node:fs');
const webAppSource = require('./web_app_source.cjs');
const path = require('node:path');
const {JSDOM} = require('jsdom');
const root = path.resolve(__dirname, '..');
const fixtures = JSON.parse(fs.readFileSync(process.argv[2], 'utf8'));
const dom = new JSDOM(fs.readFileSync(path.join(root, 'jeuxRPG/multiplayer/web/index.html'), 'utf8'), {url:'http://localhost',runScripts:'outside-only'});
dom.window.setInterval = () => 0;
dom.window.fetch = () => new Promise(() => {});
dom.window.eval(fs.readFileSync(path.join(root,'jeuxRPG/multiplayer/web/map_artwork.js'),'utf8'));
dom.window.eval(webAppSource(root) + `
window.mountHud = adventure => {session={id:'hud',me:'p0',tutorial:adventure,events:[]};renderTutorial(adventure);};
window.hudCalls=[];tutorialCommand=async (action,params)=>window.hudCalls.push({action,params});
`);
const el = id => dom.window.document.getElementById(id);
(async () => {
  const adventure = JSON.parse(JSON.stringify(fixtures.combat));
  dom.window.mountHud(adventure);
  const attack = el('skill-main-attack').firstElementChild;
  const favorite = el('skill-offense').firstElementChild;
  const vitals = el('combat-resources').querySelector('.vitals-card');
  const status = vitals.querySelector('.vitals-statuses').firstElementChild;
  attack.focus();
  for (let i=0;i<30;i++) dom.window.mountHud(adventure);
  assert.strictEqual(el('skill-main-attack').firstElementChild, attack);
  assert.strictEqual(el('skill-offense').firstElementChild, favorite);
  assert.strictEqual(dom.window.document.activeElement, attack);
  assert.strictEqual(vitals.querySelector('.vitals-statuses').firstElementChild,status);
  favorite.dispatchEvent(new dom.window.MouseEvent('pointerdown',{button:0,bubbles:true}));
  await new Promise(resolve=>setTimeout(resolve,200));
  dom.window.mountHud(adventure);
  await new Promise(resolve=>setTimeout(resolve,260));
  assert.equal(el('skill-popover').hidden,false);
  favorite.dispatchEvent(new dom.window.MouseEvent('pointerup',{button:0,bubbles:true}));
  assert.equal(dom.window.hudCalls.length,0);
  const choice=el('skill-popover').firstElementChild;
  for(let i=0;i<10;i++) dom.window.mountHud(adventure);
  assert.strictEqual(el('skill-popover').firstElementChild,choice);
  assert.equal(el('skill-popover').hidden,false);
  attack.click();
  assert.equal(dom.window.hudCalls.length,1);
  assert.equal(dom.window.hudCalls[0].action,'strike');
  process.stdout.write('HUD : boutons stables, focus, PV inchangés et appui long préservés après 40 actualisations.\n');
})().catch(error=>{console.error(error);process.exitCode=1;}).finally(()=>dom.window.close());
