const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const {JSDOM, VirtualConsole} = require("jsdom");
const root = path.resolve(__dirname, "..");
const fixture = JSON.parse(fs.readFileSync(process.argv[2], "utf8"));
const errors = [];
const virtualConsole = new VirtualConsole();
virtualConsole.on("jsdomError", error => errors.push(error.message));
const dom = new JSDOM(fs.readFileSync(path.join(root, "multiplayer/web/index.html"), "utf8"), {url: "http://127.0.0.1:8080", runScripts: "outside-only", virtualConsole});
dom.window.setInterval = () => 0;
dom.window.eval(fs.readFileSync(path.join(root, "multiplayer/web/app.js"), "utf8") + `
window.uiTest = {calls: [], render: adventure => {session = {id: "ui", me: "p0", tutorial: adventure}; renderTutorial(adventure);}};
tutorialCommand = async (action, params) => window.uiTest.calls.push({action, params});
`);
const el = id => dom.window.document.getElementById(id);
const render = value => dom.window.uiTest.render(JSON.parse(JSON.stringify(value)));
const event = (node, name) => node.dispatchEvent(new dom.window.MouseEvent(name, {bubbles: true}));
const unit = id => el("world-map").querySelector(`[data-unit="${id}"]`);
try {
  render(fixture);
  assert.equal(el("mob-cards").children.length, 3);
  event(unit("mob"), "click");
  assert.equal(el("combat-target").options.length, 1);
  assert.equal(el("combat-target").value, "mob");
  assert(el("world-map").querySelector(".objective-ring"));
  el("combat-actions").querySelector("button").click();
  assert.equal(dom.window.uiTest.calls.at(-1).params.target, "mob");
  event(unit("mob"), "click");
  assert.equal(el("combat-actions").children.length, 0);
  assert.equal(el("combat-target").value, "");
  assert(!el("world-map").querySelector(".objective-ring"));
  event(unit("mob-3"), "click");
  assert.equal(el("combat-actions").children.length, 0);
  assert.equal(el("combat-target").options.length, 0);
  event(unit("mob-3"), "dblclick");
  const movement = dom.window.uiTest.calls.at(-1);
  assert.equal(movement.action, "battle_move");
  assert(movement.params.path.length > 0);
  assert(Math.hypot(movement.params.x - 12, movement.params.y - 5) <= 1.5);
  const near = JSON.parse(JSON.stringify(fixture));
  near.battle.corpses = [{id: "dead", name: "Gobelin mort", position: [9, 4], harvested: ["p0"]}];
  near.battle.summons = {"p0:summon:0": {position: [8, 4], name: "Squelette", hp: 10, max_hp: 10}};
  render(near);
  assert(el("corpse-actions").textContent.includes("déjà dépecé"));
  assert(unit("p0:summon:0"));
  const far = JSON.parse(JSON.stringify(near));
  far.battle.players.p0.position = [0, 0];
  render(far);
  assert(!el("corpse-actions").textContent.includes("déjà dépecé"));
  assert(!el("tactical-actions").textContent.includes("Se cacher"));
  far.battle.players.p0.position = [2, 5];
  render(far);
  assert(el("tactical-actions").textContent.includes("Se cacher"));
  far.players[0].casting = {name: "Sort", remaining_seconds: 1.4, concentration: true};
  render(far);
  assert(el("combat-status").textContent.includes("1.4 s"));
  assert(!el("tactical-actions").textContent.includes("Se cacher"));
  const previous = dom.window.uiTest.calls.length;
  event(unit("mob-3"), "dblclick");
  assert.equal(dom.window.uiTest.calls.length, previous);
  assert.equal(errors.length, 0, errors.join(" · "));
  console.log("UI tactique : focus exclusif, désélection, double clic, corps proches, couverture, incantation et squelette vérifiés.");
} finally {
  dom.window.close();
}
