const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const {JSDOM, VirtualConsole} = require("jsdom");
const root = path.resolve(__dirname, "..");
const fixtures = JSON.parse(fs.readFileSync(process.argv[2], "utf8"));
const fixture = fixtures.combat;
const errors = [];
const virtualConsole = new VirtualConsole();
virtualConsole.on("jsdomError", error => errors.push(error.message));
const dom = new JSDOM(fs.readFileSync(path.join(root, "multiplayer/web/index.html"), "utf8"), {url: "http://127.0.0.1:8080", runScripts: "outside-only", virtualConsole});
dom.window.setInterval = () => 0;
dom.window.eval(fs.readFileSync(path.join(root, "multiplayer/web/map_artwork.js"), "utf8"));
dom.window.eval(fs.readFileSync(path.join(root, "multiplayer/web/app.js"), "utf8") + `
window.uiTest = {gridPath, calls: [], world: adventure => {worldCameras.clear(); mapPlace = adventure.world.places[0].id; renderWorld(adventure, adventure.players[0]);}, render: (adventure, events = []) => {session = {id: "ui", me: "p0", tutorial: adventure, events}; renderTutorial(adventure);}};
tutorialCommand = async (action, params) => window.uiTest.calls.push({action, params});
`);
const el = id => dom.window.document.getElementById(id);
const render = (value, events = []) => dom.window.uiTest.render(JSON.parse(JSON.stringify(value)), events);
const event = (node, name) => node.dispatchEvent(new dom.window.MouseEvent(name, {bubbles: true}));
const unit = id => el("world-map").querySelector(`[data-unit="${id}"]`);
try {
  const openMap = {width: 4, height: 4, cover: []};
  assert.equal(JSON.stringify(dom.window.uiTest.gridPath(openMap, [0,0], [2,2])), "[[1,1],[2,2]]");
  openMap.cover = [[1,0]];
  assert.equal(JSON.stringify(dom.window.uiTest.gridPath(openMap, [0,0], [1,1])), "[[0,1],[1,1]]");
  render(fixture, [{id: 1, game_time: 99, message: "Joueur repéré par Gobelin."}, {id: 2, game_time: 100, message: "Gobelin utilise Entaille : 3 PV perdus."}]);
  assert(el("combat-notice").textContent.includes("3 PV perdus"));
  assert(!el("combat-feedback").querySelector("details").open);
  assert(el("skills").compareDocumentPosition(el("combat-feedback")) & dom.window.Node.DOCUMENT_POSITION_FOLLOWING);
  assert(el("combat-events").textContent.includes("repéré"));
  assert.equal(el("mob-cards").children.length, 3);
  const automatic = JSON.parse(JSON.stringify(fixture));
  automatic.mobs[0].stats.hp.current = 0;
  automatic.mobs[1].stats.hp.current = 8;
  automatic.mobs[2].stats.hp.current = 2;
  render(automatic);
  assert.equal(el("combat-target").value, "mob-2");
  event(unit("mob-3"), "click");
  automatic.mobs[2].stats.hp.current = 0;
  render(automatic);
  assert.equal(el("combat-target").value, "mob-2");
  assert.equal(el("combat-auto-target").getAttribute("aria-pressed"), "true");
  event(unit("mob-3"), "click");
  assert.equal(el("combat-target").value, "mob-2");
  const removed = JSON.parse(JSON.stringify(fixture));
  render(removed);
  event(unit("mob-3"), "click");
  removed.mobs = removed.mobs.filter(mob => mob.combat_id !== "mob-3");
  removed.battle.corpses = [{id: "mob-3", name: "Gobelin", position: [2,2]}];
  render(removed);
  assert.notEqual(el("combat-target").value, "mob-3");
  assert.equal(el("combat-auto-target").getAttribute("aria-pressed"), "true");
  const support = JSON.parse(JSON.stringify(fixture));
  const rangeTest = JSON.parse(JSON.stringify(fixture));
  rangeTest.step = "auto-range-test";
  rangeTest.players[0].skills = [];
  rangeTest.players[0].can_attack = true;
  rangeTest.players[0].attack_range = 2;
  rangeTest.players[0].cooldown_real_seconds = 0;
  rangeTest.battle.players.p0.position = [1,1];
  rangeTest.battle.map.cover = [];
  rangeTest.battle.map.blocked = [];
  rangeTest.mobs[0].position = [18,18];
  rangeTest.mobs[0].stats.hp.current = 1;
  rangeTest.mobs[1].position = [2,1];
  rangeTest.mobs[1].stats.hp.current = 8;
  rangeTest.mobs[2].stats.hp.current = 0;
  render(rangeTest);
  assert.equal(el("combat-target").value, "mob-2");
  rangeTest.mobs[1].position = [18,17];
  rangeTest.mobs[0].position = [2,1];
  render(rangeTest);
  assert.equal(el("combat-target").value, "mob");
  support.step = "auto-support-test";
  const healer = support.players[0];
  healer.hp = Math.max(1, healer.max_hp - 1);
  healer.skills.push({name: "Soin test", type: "HEAL", available: true, cooldown: 0, energy: healer.energies[0].type, cost: 0, range: 0, targets: [healer.id], can_target_others: false});
  render(support);
  assert.equal(el("combat-target").value, healer.id);
  healer.hp = healer.max_hp;
  render(support);
  assert.equal(el("combat-target").value, "mob");
  event(unit("mob"), "click");
  healer.hp -= 1;
  render(support);
  assert.equal(el("combat-target").value, "mob");
  event(unit("mob"), "click");
  support.mobs[0].stats.hp.current = 0;
  render(support);
  assert.equal(el("combat-target").value, healer.id);
  healer.hp = healer.max_hp;
  healer.skills.at(-1).type = "BUFF";
  render(support);
  assert.equal(el("combat-target").value, healer.id);
  healer.skills.at(-1).cost = healer.energies[0].current + 1;
  render(support);
  assert.notEqual(el("combat-target").value, healer.id);
  render(fixture);
  const retainedDetails = el("character-details").firstElementChild;
  const retainedIntents = el("enemy-intents").firstElementChild;
  const retainedMap = el("world-map").firstElementChild;
  render(fixture);
  assert.equal(el("character-details").firstElementChild, retainedDetails);
  assert.equal(el("enemy-intents").firstElementChild, retainedIntents);
  assert.equal(el("world-map").firstElementChild, retainedMap);
  event(unit("mob"), "click");
  assert.equal(el("combat-target").options.length, 1);
  assert.equal(el("combat-target").value, "mob");
  assert(el("world-map").querySelector(".objective-ring"));
  el("combat-actions").querySelector("button").click();
  assert.equal(dom.window.uiTest.calls.at(-1).params.target, "mob");
  event(unit("mob"), "click");
  assert(!el("combat-actions").querySelector("button").disabled);
  assert.equal(el("combat-target").value, "mob");
  assert(!el("world-map").querySelector(".objective-ring"));
  event(unit("mob-3"), "click");
  assert([...el("combat-actions").children].every(button => button.disabled));
  assert.equal(el("combat-target").value, "mob-3");
  event(unit("mob-3"), "dblclick");
  const movement = dom.window.uiTest.calls.at(-1);
  assert.equal(movement.action, "battle_move");
  assert(movement.params.path.length > 0);
  assert(Math.hypot(movement.params.x - 12, movement.params.y - 5) <= 1.5);
  const moving = JSON.parse(JSON.stringify(fixture));
  moving.players[0].cooldown_real_seconds = 1;
  moving.battle.players.p0.route = [];
  render(moving);
  const beforeRedirect = dom.window.uiTest.calls.length;
  event(unit("mob-3"), "dblclick");
  assert.equal(dom.window.uiTest.calls.length, beforeRedirect + 1);
  assert.equal(dom.window.uiTest.calls.at(-1).action, "battle_move");
  assert(unit("p0"));
  assert.equal(el("combat-allies").parentElement.id, "combat-player-panel");
  assert.equal(el("unit-controls").parentElement.id, "combat-player-panel");
  assert.equal(el("combat-view").parentElement.id, "combat-action-panel");
  assert.equal(el("combat-enemies").parentElement.id, "combat-enemy-panel");
  const attackSlot = el("combat-actions").querySelector("button");
  const recoveringKnight = JSON.parse(JSON.stringify(moving));
  recoveringKnight.players[0].cooldown_real_seconds = .5;
  render(recoveringKnight);
  assert.equal(el("combat-actions").querySelector("button"), attackSlot);
  assert(attackSlot.disabled);
  assert(el("skills").children.length > 0);
  const afflicted = JSON.parse(JSON.stringify(fixture));
  afflicted.players[0].effects = [{name: "Poison", duration: 3, remaining_seconds: 2.3, group: "debuff"}];
  afflicted.mobs[0].effects = [{name: "Faiblesse", duration: 2, group: "debuff"}];
  render(afflicted);
  assert(el("character-details").textContent.includes("Poison"));
  assert(el("combat-resources").textContent.includes("Poison (2.3 s)"));
  assert.equal(el("combat-resources").querySelectorAll(".vitals-card").length, afflicted.players.length);
  const resources = el("combat-resources").querySelector(".vitals-card");
  assert.equal(resources.querySelectorAll("progress").length, 1 + afflicted.players[0].energies.length);
  assert.equal(resources.querySelector("progress").value, afflicted.players[0].hp);
  assert.equal(resources.querySelector("progress").max, afflicted.players[0].max_hp);
  const extraEnergy = JSON.parse(JSON.stringify(afflicted));
  extraEnergy.players[0].energies.push({type: "Mana", current: 4, max: 12});
  render(extraEnergy);
  assert.equal(el("combat-resources").querySelector(".vitals-card").querySelectorAll("progress").length, 1 + extraEnergy.players[0].energies.length);
  assert(el("combat-resources").textContent.includes("4/12 Mana"));
  assert(el("mob-cards").textContent.includes("Faiblesse"));
  const near = JSON.parse(JSON.stringify(fixture));
  near.battle.corpses = [{id: "dead", name: "Gobelin mort", position: [9, 4], harvested: ["p0"]}];
  near.battle.summons = {"p0:summon:0": {position: [8, 4], name: "Squelette", hp: 10, max_hp: 10}};
  render(near);
  assert(Boolean(el("corpse-actions").querySelector('button[aria-label*="déjà dépecé"]')));
  assert(unit("p0:summon:0"));
  const far = JSON.parse(JSON.stringify(near));
  far.battle.players.p0.position = [0, 0];
  render(far);
  assert(!Boolean(el("corpse-actions").querySelector('button[aria-label*="déjà dépecé"]')));
  assert(!Boolean(el("tactical-actions").querySelector('button[aria-label*="Se cacher"]')));
  far.battle.players.p0.position = [2, 5];
  far.battle.players.p0.can_hide = true;
  render(far);
  assert(Boolean(el("tactical-actions").querySelector('button[aria-label*="Se cacher"]')));
  far.players[0].casting = {name: "Sort", remaining_seconds: 1.4, concentration: true};
  render(far);
  assert(el("combat-status").textContent.includes("1.4 s"));
  assert(!Boolean(el("tactical-actions").querySelector('button[aria-label*="Se cacher"]')));
  const previous = dom.window.uiTest.calls.length;
  event(unit("mob-3"), "dblclick");
  assert.equal(dom.window.uiTest.calls.length, previous);
  const necromancer = fixtures.necromancer;
  render(necromancer);
  const summon = el("self-skills").querySelector("button");
  assert(summon && !summon.disabled);
  assert.equal(el("combat-target").value, "");
  event(unit("p0"), "click");
  summon.focus();
  for (let refresh = 0; refresh < 12; refresh++) {
    render(necromancer);
    assert.equal(el("self-skills").querySelector("button"), summon);
    assert.equal(dom.window.document.activeElement, summon);
    assert.equal(el("combat-target").value, "p0");
  }
  event(summon, "mousedown");
  render(necromancer);
  event(summon, "mouseup");
  summon.click();
  assert.equal(dom.window.uiTest.calls.at(-1).action, "skill");
  assert.equal(dom.window.uiTest.calls.at(-1).params.skill_name, "Low Skull");
  assert.equal(dom.window.uiTest.calls.at(-1).params.target, "p0");
  event(unit("p0"), "click");
  summon.click();
  assert.equal(dom.window.uiTest.calls.at(-1).params.target, "p0");
  const recovering = JSON.parse(JSON.stringify(necromancer));
  recovering.players[0].cooldown_real_seconds = .5;
  recovering.players[0].skills[0].targets = [];
  render(recovering);
  assert.equal(el("self-skills").querySelector("button"), summon);
  assert(summon.disabled);
  render(necromancer);
  assert(!summon.disabled);
  const control = fixtures.control;
  render(control);
  const summonId = Object.keys(control.battle.summons)[0];
  assert(!el("unit-controls").hidden);
  assert(el("combat-stats-details").textContent.includes("Squelette"));
  assert(!el("combat-allies").textContent.includes("Force"));
  assert(el("combat-stats-details").textContent.includes("PV"));
  event(unit(summonId), "click");
  assert.equal(dom.window.uiTest.calls.at(-1).action, "control_units");
  assert.deepEqual([...dom.window.uiTest.calls.at(-1).params.units], [summonId]);
  assert(el("cell-entities").textContent.includes("Squelette"));
  assert(el("selected-unit-stats").textContent.includes("0.4 Mana/s"));
  control.battle.summons[summonId].controlled = true;
  control.battle.summons[summonId].route = [];
  render(control);
  assert(el("combat-action-title").textContent.includes("Squelette"));
  assert.equal(el("self-skills").children.length, 0);
  assert(el("skills").textContent.includes("Sword Slash"));
  const stableUnit = unit("mob");
  const stableCircle = stableUnit.querySelector("circle");
  const stableMap = el("world-map").querySelector("svg");
  event(unit("mob"), "click");
  const observer = new dom.window.MutationObserver(() => {});
  observer.observe(el("world-map"), {subtree: true, childList: true});
  render(control);
  assert(!observer.takeRecords().some(record => [...record.removedNodes].includes(stableUnit) || [...record.removedNodes].includes(stableCircle)));
  observer.disconnect();
  assert.equal(unit("mob"), stableUnit);
  assert.equal(unit("mob").querySelector("circle"), stableCircle);
  assert.equal(el("world-map").querySelector("svg"), stableMap);
  const moveCell = el("world-map").querySelector('[data-cell="11,1"]');
  const previousOrders = dom.window.uiTest.calls.length;
  event(moveCell, "click");
  assert.equal(dom.window.uiTest.calls.length, previousOrders);
  assert(el("cell-selection-status").textContent.includes("Aucune entité visible"));
  assert.equal(el("combat-target").value, "mob");
  event(moveCell, "dblclick");
  assert.equal(dom.window.uiTest.calls.at(-1).action, "unit_order");
  assert.equal(dom.window.uiTest.calls.at(-1).params.order, "move");
  assert.deepEqual([...dom.window.uiTest.calls.at(-1).params.target], [11, 1]);
  event(unit("mob"), "click");
  event(unit("mob"), "click");
  assert.equal(el("cell-entities").querySelectorAll("button").length, 1);
  [...el("combat-actions").querySelectorAll("button")].find(b => b.textContent.includes("invocation")).click();
  assert.equal(dom.window.uiTest.calls.at(-1).params.order, "attack");
  assert.equal(dom.window.uiTest.calls.at(-1).params.target, "mob");
  const closeSkillTarget = JSON.parse(JSON.stringify(control));
  closeSkillTarget.mobs[0].position = [11, 1];
  render(closeSkillTarget);
  const invocationSkill = el("skills").querySelector("button");
  assert(invocationSkill && !invocationSkill.disabled);
  invocationSkill.click();
  assert.equal(dom.window.uiTest.calls.at(-1).action, "unit_skill");
  assert.equal(dom.window.uiTest.calls.at(-1).params.skill_name, "Sword Slash");
  assert.deepEqual([...dom.window.uiTest.calls.at(-1).params.units], [summonId]);
  assert(!el("combat-allies").textContent.includes("Force"));
  const groupControl = JSON.parse(JSON.stringify(control));
  const secondId = "p0:summon:1";
  groupControl.battle.summons[secondId] = JSON.parse(JSON.stringify(groupControl.battle.summons[summonId]));
  render(groupControl);
  event(el("world-map").querySelector('[data-cell="10,1"]'), "click");
  const candidates = [...el("cell-entities").querySelectorAll("button")];
  assert.equal(candidates.length, 2);
  assert.notEqual(candidates[0].textContent, candidates[1].textContent);
  [...el("unit-control-actions").querySelectorAll("button")].find(b => b.textContent === "Tout contrôler").click();
  assert.equal(dom.window.uiTest.calls.at(-1).params.units.length, 2);
  render(control);
  event(unit("mob"), "click");
  const invisible = JSON.parse(JSON.stringify(control));
  invisible.mobs = []; invisible.mob = null; invisible.battle.intents = [];
  render(invisible);
  assert.equal(el("cell-entities").querySelectorAll("[data-target=mob]").length, 0);
  assert([...el("combat-actions").children].every(button => button.disabled));
  render(fixture);
  const legacyBox = el("world-map").querySelector("svg").getAttribute("viewBox");
  el("field-zoom-in").click();
  const legacyZoom = el("world-map").querySelector("svg").getAttribute("viewBox");
  assert.notEqual(legacyZoom, legacyBox);
  render(fixture);
  assert.equal(el("world-map").querySelector("svg").getAttribute("viewBox"), legacyZoom);
  const peaceful = JSON.parse(JSON.stringify(fixture));
  peaceful.battle = null; peaceful.mobs = []; peaceful.mob = null;
  render(peaceful);
  const general = el("world-map").querySelector('[data-map="general"]');
  const generalBox = general.getAttribute("viewBox");
  event(general, "click");
  el("field-zoom-in").click();
  const generalZoom = general.getAttribute("viewBox");
  assert.notEqual(generalZoom, generalBox);
  peaceful.players[0].hp -= 1;
  render(peaceful);
  assert.equal(el("world-map").querySelector('[data-map="general"]').getAttribute("viewBox"), generalZoom);
  const detail = el("world-map").querySelector('[data-map^="detail:"]');
  if (detail) {
    const detailBox = detail.getAttribute("viewBox");
    event(detail, "click"); el("field-zoom-in").click();
    assert.notEqual(detail.getAttribute("viewBox"), detailBox);
  }
  const authoredPlan = JSON.parse(JSON.stringify(peaceful));
  const authoredPlace = authoredPlan.world.places[0];
  authoredPlace.x = 800; authoredPlace.y = 500; authoredPlace.entry = [120, 230];
  authoredPlace.points = [{id: "clearing_fight", name: "Point modifié", type: "rencontre", x: 900, y: 700}];
  dom.window.uiTest.world(authoredPlan);
  const authoredGeneral = el("world-map").querySelector('[data-map="general"]');
  const authoredDetail = el("world-map").querySelector('[data-map^="detail:"]');
  assert(Number(authoredGeneral.getAttribute("viewBox").split(" ")[2]) > 800);
  assert(Number(authoredDetail.getAttribute("viewBox").split(" ")[3]) > 700);
  assert.equal(authoredDetail.querySelector("circle").getAttribute("cx"), "120");
  assert.equal(authoredDetail.querySelector('[data-point="clearing_fight"] circle').getAttribute("cy"), "700");
  assert(authoredDetail.textContent.includes("Point modifié"));
  if (fixtures.field_village) {
    render(fixtures.field_village);
    assert.equal(el("field-camera").hidden, false);
    assert.equal(el("field-location").textContent, "Village de Rosée");
    assert(el("world-map").querySelector('[data-site="mira"]'));
    assert(el("world-map").querySelector(".unexplored-cell"));
    const initialBox = el("world-map").querySelector("svg").getAttribute("viewBox");
    el("field-zoom-in").click();
    assert.notEqual(el("world-map").querySelector("svg").getAttribute("viewBox"), initialBox);
    for (const direction of ["left", "up", "down", "right"]) assert.equal(el(`field-${direction}`), null);
    el("field-center").click();
    assert.equal(el("npc-view").hidden, false);
    assert.equal(el("npc-view").parentElement.id, "combat-action-panel");
    assert.equal(el("target-controls").hidden, true);
  }
  if (fixtures.field_village) {
    const scene = JSON.parse(JSON.stringify(fixtures.field_village));
    const gate = scene.battle.map.exits[0];
    scene.battle.explored = [];
    render(scene);
    const marker = el("world-map").querySelector(`[data-exit="${gate.position.join(",")}"]`);
    assert(marker, "Un passage doit avoir un repère visible même hors exploration et hors cadrage");
    event(marker, "dblclick");
    assert(dom.window.uiTest.calls.some(call => call.action === "battle_move" && call.params.x === gate.position[0] && call.params.y === gate.position[1]));
    scene.battle.map.exits.push({...gate, position: [gate.position[0], gate.position[1] + 1], name: "Autre passage"});
    render(scene);
    const markers = [...el("world-map").querySelectorAll("[data-exit]")];
    assert.equal(markers.length, scene.battle.map.exits.length);
    const circles = markers.map(marker => marker.querySelector("circle"));
    for (let i = 0; i < circles.length; i++) for (let j = i + 1; j < circles.length; j++) assert(Number(circles[i].getAttribute("cx")) !== Number(circles[j].getAttribute("cx")) || Number(circles[i].getAttribute("cy")) !== Number(circles[j].getAttribute("cy")));
    if (scene.battle.map.bridges?.length) {
      const bridge = scene.battle.map.bridges[0];
      scene.battle.map.bridge_rotations = [{position: bridge, rotation: 90}];
      scene.battle.players[scene.players[0].id].position = bridge;
      scene.battle.explored.push(bridge);
      render(scene);
      const cell = el("world-map").querySelector(`[data-cell="${bridge.join(",")}"]`);
      assert.equal(cell.dataset.rotation, "90");
      assert(cell.classList.contains("bridge-rotation-90"));
      assert.equal(cell.hasAttribute("style"), false);
      const textures = el("world-map").querySelector("defs");
      render(scene);
      assert.strictEqual(el("world-map").querySelector("defs"), textures);
      assert.strictEqual(el("world-map").querySelector(`[data-cell="${bridge.join(",")}"]`), cell);
      assert(el("world-map").querySelector("#river-bridge-90"));
    }
    let requested = 0;
    el("battle").requestFullscreen = () => { requested++; return Promise.resolve(); };
    event(el("battle"), "pointerdown");
    event(el("battle"), "pointerdown");
    assert.equal(requested, 0);
  }
  assert.equal(errors.length, 0, errors.join(" · "));
  console.log("UI tactique : ciblage automatique, soin/buff autorisés, focus manuel conservé, désélection, double clic, corps proches, couverture, incantation, squelette et invocation stable pendant les actualisations vérifiés.");
} finally {
  dom.window.close();
}
