const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const {JSDOM} = require(require.resolve('jsdom', {paths:[path.join(__dirname,'..','.ui-test'),__dirname]}));
const dom = new JSDOM('<section id="battle"></section>', {runScripts:'outside-only'});
const w = dom.window;
let now=0, timer=null, moves=0, stops=0, clicks=0;
const state={active:true,busy:false,key:'room:1',actor:{route:[]}};
w.Date.now=()=>now;
w.setInterval=callback=>{assert.equal(timer,null); timer=callback; return 1;};
w.clearInterval=()=>{timer=null;};
w.eval(fs.readFileSync(path.join(__dirname,'../jeuxRPG/multiplayer/web/mobile_controls.js'),'utf8'));
const source=w.document.createElement('button');
source.textContent='Attaque simple'; source.onclick=()=>{clicks++;};
const controls=w.createRpgTouchControls({state:()=>state,move:()=>{moves++;return true;},stop:()=>{stops++;},actions:()=>[source]});
controls.sync();
assert.equal(timer,null);
const stick=w.document.getElementById('touch-stick');
stick.getBoundingClientRect=()=>({left:0,top:0,width:100,height:100});
function pointer(type,x,y,id=1){const event=new w.Event(type,{cancelable:true});Object.assign(event,{pointerId:id,clientX:x,clientY:y});stick.dispatchEvent(event);}
pointer('pointerdown',100,50);
assert.equal(moves,1);
for(let i=0;i<200;i++) pointer('pointermove',100,50);
assert.equal(moves,1);
for(now=100;now<1000;now+=100) timer();
assert.equal(moves,4);
state.actor.route=[[1,0]];
for(now=1000;now<2000;now+=100) timer();
assert.equal(moves,4);
state.busy=true;
pointer('pointerup',100,50);
assert.equal(stops,0);
state.busy=false; now=2100; timer();
assert.equal(stops,1); assert.equal(timer,null);
controls.sync();
w.document.querySelector('#touch-actions button').click();
assert.equal(clicks,1);
source.disabled=true; controls.sync();
w.document.querySelector('#touch-actions button').click();
assert.equal(clicks,1);
pointer('pointerdown',100,50);
state.key='room:2'; timer();
assert.equal(timer,null);
state.actor.route=[]; state.actor.position=[0,0]; now=3000;
pointer('pointerdown',100,50);
const sent=moves;
for(now=3100;now<4000;now+=100) timer();
assert.equal(moves,sent);
state.actor.position=[1,0]; now=4100; timer();
assert.equal(moves,sent+1);
pointer('pointerup',100,50); now=4400; timer?.();
assert.equal(w.document.querySelectorAll('[style]').length,0);
dom.window.close();
console.log('Joystick : rafales locales regroupées, maximum quatre déplacements/s, route réutilisée, arrêt et actions rapides vérifiés.');
