const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const {JSDOM} = require('jsdom');
const root = path.join(__dirname, '..', 'multiplayer', 'web');
const dom = new JSDOM(fs.readFileSync(path.join(root, 'admin.html'), 'utf8'), {url: 'https://rpg.test/admin', runScripts: 'outside-only'});
const {window} = dom;
const calls = [];
let suspended = false;
window.fetch = async (url, options) => {
  calls.push({url, options});
  if (options.method === 'POST') suspended = true;
  return {ok: true, status: 200, json: async () => options.method === 'GET' ? {accounts: [{id: 'a'.repeat(32), name: '<img src=x onerror=alert(1)>', class_name: 'Knight', suspended}], has_more: false} : {ok: true}};
};
window.eval(fs.readFileSync(path.join(root, 'admin.js'), 'utf8'));
const el = id => window.document.getElementById(id);
const submit = id => el(id).dispatchEvent(new window.Event('submit', {bubbles: true, cancelable: true}));
const settle = () => new Promise(resolve => setImmediate(resolve));
(async () => {
  el('admin-token').value = 'secret-admin-test';
  submit('login-form'); await settle();
  assert.equal(el('panel').hidden, false);
  assert.equal(el('admin-token').value, '');
  assert.equal(window.localStorage.length, 0);
  assert.equal(window.sessionStorage.length, 0);
  assert.equal(window.document.querySelectorAll('img').length, 0);
  assert.equal(el('next').disabled, true);
  const buttons = Array.from(el('accounts').querySelectorAll('button'));
  buttons.find(button => button.textContent === 'Suspendre').click();
  assert.equal(el('edit').hidden, false);
  assert.equal(calls.filter(call => call.options.method === 'POST').length, 0);
  submit('edit-form'); await settle();
  assert.equal(calls.filter(call => call.options.method === 'POST').length, 1);
  assert.equal(JSON.parse(calls.find(call => call.options.method === 'POST').options.body).action, 'suspend');
  assert.match(el('accounts').textContent, /Suspendu/);
  el('logout').click();
  assert.equal(el('login').hidden, false);
  assert.equal(el('accounts').children.length, 0);
  console.log('Interface admin : connexion, confirmation, suspension, texte sûr, pagination et déconnexion validés.');
  window.close();
})().catch(error => {console.error(error); process.exitCode = 1; window.close();});
